package bean;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "user".
 */
@Entity(nameInDb = "user")
public class UserBean {

    @Id(autoincrement = true)
    private Long id;
    private String name;
    private Boolean gender;
    private Integer age;

    @Generated
    public UserBean() {
    }

    public UserBean(Long id) {
        this.id = id;
    }

    @Generated
    public UserBean(Long id, String name, Boolean gender, Integer age) {
        this.id = id;
        this.name = name;
        this.gender = gender;
        this.age = age;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getGender() {
        return gender;
    }

    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

}
